package com.bettercast.receiver.network

import android.content.Context
import android.net.wifi.WifiManager
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.util.Log

/**
 * Hosts a local-only Wi-Fi hotspot so a Mac can reach this device with no router.
 *
 * This is the only workable direction for hotspot pairing: macOS has no public API
 * for Internet Sharing, so the Mac can never be the host. Android's
 * [WifiManager.startLocalOnlyHotspot] exists precisely for peer-to-peer app use and
 * needs no root or system permissions.
 *
 * Two things surprise people:
 *  - The SSID and passphrase are generated by the system and cannot be chosen.
 *  - Starting the hotspot disconnects this phone from Wi-Fi. It is local-only, so
 *    neither device gets internet while it is up. That is expected, not a fault.
 *
 * The hotspot lives only as long as the reservation is held, so [stop] must be called
 * or it lingers until the process dies.
 */
class HotspotManager(private val context: Context) {

    companion object {
        private const val TAG = "HotspotManager"
    }

    data class Credentials(val ssid: String, val passphrase: String)

    private val wifiManager =
        context.applicationContext.getSystemService(Context.WIFI_SERVICE) as WifiManager

    private var reservation: WifiManager.LocalOnlyHotspotReservation? = null

    val isActive: Boolean get() = reservation != null

    /**
     * Start the hotspot. Exactly one of [onReady] or [onError] is called.
     *
     * Requires CHANGE_WIFI_STATE plus, at runtime, NEARBY_WIFI_DEVICES on API 33+ or
     * ACCESS_FINE_LOCATION below that — with location services actually switched on,
     * which is a separate thing from the permission being granted.
     */
    fun start(onReady: (Credentials) -> Unit, onError: (String) -> Unit) {
        if (reservation != null) {
            credentials()?.let(onReady) ?: onError("Hotspot already running but credentials unavailable")
            return
        }

        try {
            wifiManager.startLocalOnlyHotspot(
                object : WifiManager.LocalOnlyHotspotCallback() {
                    override fun onStarted(res: WifiManager.LocalOnlyHotspotReservation) {
                        reservation = res
                        val creds = credentials()
                        if (creds == null) {
                            Log.e(TAG, "Hotspot started but no credentials were returned")
                            onError("Hotspot started but returned no credentials")
                        } else {
                            Log.d(TAG, "Hotspot started, SSID ${creds.ssid}")
                            onReady(creds)
                        }
                    }

                    override fun onStopped() {
                        Log.d(TAG, "Hotspot stopped")
                        reservation = null
                    }

                    override fun onFailed(reason: Int) {
                        reservation = null
                        val message = when (reason) {
                            ERROR_NO_CHANNEL -> "No free Wi-Fi channel. Turn Wi-Fi off and retry."
                            ERROR_GENERIC -> "The system refused to start a hotspot."
                            ERROR_INCOMPATIBLE_MODE -> "Hotspot is not available while tethering is on."
                            ERROR_TETHERING_DISALLOWED -> "Tethering is disabled on this device or by your carrier."
                            else -> "Hotspot failed to start (code $reason)."
                        }
                        Log.e(TAG, "Hotspot failed: $message")
                        onError(message)
                    }
                },
                Handler(Looper.getMainLooper())
            )
        } catch (e: SecurityException) {
            // Thrown when the runtime permission is missing or location is switched off.
            Log.e(TAG, "Hotspot permission denied", e)
            onError("Permission denied. Grant nearby-devices or location access, and switch location on.")
        } catch (e: IllegalStateException) {
            Log.e(TAG, "Hotspot unavailable", e)
            onError("Hotspot unavailable right now. Turn Wi-Fi off and try again.")
        }
    }

    fun stop() {
        reservation?.close()
        reservation = null
        Log.d(TAG, "Hotspot released")
    }

    @Suppress("DEPRECATION")
    private fun credentials(): Credentials? {
        val res = reservation ?: return null
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
            val config = res.softApConfiguration
            val ssid = config.ssid ?: return null
            val pass = config.passphrase ?: return null
            Credentials(ssid.trim('"'), pass)
        } else {
            val config = res.wifiConfiguration ?: return null
            val ssid = config.SSID ?: return null
            val pass = config.preSharedKey ?: return null
            Credentials(ssid.trim('"'), pass.trim('"'))
        }
    }
}
